## Now You Code 2: Syracuse Crime Data

In this second now you code you will explore the plot.ly engine in detail using Syracuse, NY FBI crime data.

In [1]:
import plotly.plotly as py    
import plotly.graph_objs as go  
import cufflinks as cf
import pandas as pd

In [2]:
crime = pd.read_csv('https://raw.githubusercontent.com/mafudge/datasets/master/crime/syracuse-crime-data-1985-2012.csv')
crime.sample(10)

,Year,Months,Population,Violent crime total,Murder and nonnegligent Manslaughter,Forcible rape,Robbery,Aggravated assault,Property crime total,Burglary,...,Violent Crime rate,Murder and nonnegligent manslaughter rate,Forcible rape rate,Robbery rate,Aggravated assault rate,Property crime rate,Burglary rate,Larceny-theft rate,Motor vehicle theft rate,Unnamed: 21
15,2000,12,147306,1565,18,47,452,1048,7565,1846,...,1062.4,12.2,31.9,306.8,711.4,5135.6,1253.2,3354.2,528.2,NaN
16,2001,12,147577,1562,15,42,567,938,7905,1810,...,1058.4,10.2,28.5,384.2,635.6,5356.5,1226.5,3519.5,610.5,NaN
24,2009,12,137208,1343,18,70,403,852,5779,1946,...,978.8,13.1,51.0,293.7,621.0,4211.9,1418.3,2547.2,246.3,NaN
12,1997,12,159610,1430,15,55,586,774,9075,2388,...,895.9,9.4,34.5,367.1,484.9,5685.7,1496.1,3731.6,458.0,NaN
11,1996,12,160033,1398,15,62,579,742,9601,2821,...,873.6,9.4,38.7,361.8,463.7,5999.4,1762.8,3711.7,524.9,NaN
8,1993,12,163626,1361,18,79,561,703,9754,2824,...,831.8,11.0,48.3,342.9,429.6,5961.2,1725.9,3885.7,349.6,NaN
20,2005,12,143306,1570,19,73,554,924,6486,1867,...,1095.6,13.3,50.9,386.6,644.8,4526.0,1302.8,2539.3,683.9,NaN
22,2007,12,139880,1435,19,67,446,903,5964,1785,...,1025.9,13.6,47.9,318.8,645.6,4263.7,1276.1,2586.5,401.1,NaN
19,2004,12,144278,1312,16,68,447,781,6609,1678,...,909.4,11.1,47.1,309.8,541.3,4580.7,1163.0,2628.3,789.4,NaN
18,2003,12,145411,1383,17,44,477,845,7773,1975,...,951.1,11.7,30.3,328.0,581.1,5345.5,1358.2,3171.7,815.6,NaN

In [3]:
# Make a line plot of population over the years, using cufflinks crime.iplot()
# set the titles on x "Year, Y "Population" and cart title " Syracuse Population" 
# TODO: replace the ???? with appropriate values to render the chart
crime.iplot(kind = 'line', x = 'Year', y = 'Population', title='Syracuse Population',xTitle='Year',yTitle='Population')

In [4]:
# Step 1:
# Now plot the same thing using plot.ly without cufflinks, again filling in the templates. Using plot.ly takes more effort but
# you have more control / flexibility over how the plots are rendered.
plot_data = [
    go.Scatter(x=crime['Year'], y=crime['Population'],mode="lines+markers", name="Syracuse Population", marker=dict(color='red')),
]

py.iplot({ 'data': plot_data,
            'layout': {
               'title': 'Syracuse Population',
               'xaxis': {
                 'title': 'Year'},
               'yaxis': {
                'title': 'Population'}
        }})

In [5]:
# Step 2:
# Now create a line plot of "Robbery rate" versus "Motor vehicle theft rate" over time.
# NOTE: you will need two series in your plot_data 
plot_data = [
    go.Scatter(x=crime['Year'], y=crime['Robbery rate'], mode="lines+markers", name="Robbery vs. Motor Vechicle Theft Rate", markers)
go.Scatter(x=crime['Year'], y=crime['Motor Vehicle theft rate'], mode="lines+markers", name="Robbery vs. Motor Vechicle Theft Rate"
           
    py.iplot(('data': plot data,
             'layout': {
               'title': 'Robbery vs Motor Vehicle Theft Rate',
               'xaxis': {
                 'title': 'Year'},
               'yaxis': {
                'title': 'Motor Vechile Theft Rate'}
             }}}

SyntaxError: invalid syntax (<ipython-input-5-86fab46831b7>, line 6)

# Interactive Plots

Finally write a program to ask for a crime metric like "Robbery" / "Burglary" / "Manslaughter" etc as input, 
then renders a plot of that metric over time as output !

Note: check to make sure the entered crime metric is in the list of Pandas columns before you attempt to plot. 
It might be a good idea to print the column names before you plot.
if it is not you should print "That is not a crime metric"

## Step 3: Problem Analysis

Inputs: Crime Metric

Outputs: Plot of that metric over time

Algorithm (Steps in Program): Name your axis with the proper titles and program spits out graph

In [8]:
## Step 4: Write code here
crime_metric = input("Enter a crime metric. ex:roberry, burglary manslaughter, so on.")

plot_data = [
    go.Scatter(x=crime['Year'], y=crime[crime_metric], mode="lines+markers", name="Syracuse crime", markers=dict(color= 'red')).

           
    py.iplot({ 'data': plot data,
             'layout': {
               'title': 'Crime in Syracuse',
               'xaxis': {
                 'title': 'Year'},
               'yaxis': {
                'title': 'Crime Metric'}
             }}}

SyntaxError: invalid syntax (<ipython-input-8-ef990a427765>, line 8)

## Reminder of Evaluation Criteria

1. What the problem attempted (analysis, code, and answered questions) ?
2. What the problem analysis thought out? (does the program match the plan?)
3. Does the code execute without syntax error?
4. Does the code solve the intended problem?
5. Is the code well written? (easy to understand, modular, and self-documenting, handles errors)